# netlify.toml untuk Proyek React / Single Page Application

[build]
  # Perintah untuk membangun (build) proyek Anda.
  # "npm run build" adalah yang paling umum.
  command = "npm run build"
  
  # Direktori tempat hasil build disimpan.
  # - Gunakan "build" jika Anda memakai Create React App.
  # - Gunakan "dist" jika Anda memakai Vite.
  # Silakan periksa nama folder di proyek Anda.
  publish = "build"

# Bagian ini SANGAT PENTING untuk aplikasi React/Vue/Angular
# Ini memastikan jika pengguna me-refresh halaman atau membuka URL selain homepage,
# situs Anda tidak akan menampilkan error 404.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
